---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-config-primary-active
  namespace: streamliner-ha
data:
  ha.yaml: |
    Monitor:
      Role: Primary
      Region: EastUS2
      Health:
        CheckpointInterval: 1m
        PreemptionHoldTime: 3m
        Checkpoint:
          URL: [STORAGE_ACCOUNT_BLOB_URL]
          ContainerName: health
    EventHub:
      Name: [EVENTHUB_NAME]
      Namespace: [EVENTHUB_NAMESPACE]
      ConsumerGroup: "$Default"
      Stategy: balanced
      Checkpoint:
        URL: [STORAGE_ACCOUNT_BLOB_URL]
        ContainerName: checks
    EventGrid:
      Primary:
        Endpoint: [EVENT_GRID_ENDPOINT]
        Topic: [EVENT_GRID_TOPIC]
        Retry:
          Delay: 1s
          MaxJitter: 3s
          Attempts: 2
        Chaos:
          Enabled: false
          Failure:
            Every: 1m
            Duration: 2m
      Secondary:
        Endpoint: [EVENT_GRID_ENDPOINT]
        Topic: [EVENT_GRID_TOPIC]
        Retry:
          Delay: 1s
          MaxJitter: 3s
          Attempts: 2
        Chaos:
          Enabled: false
          Failure:
            Every: 2m
            Duration: 1m
        # env EVENT_GRID_SECONDARY_KEY
    translate:
      adx:
        enabled: true
        endpoint: [ADX_ENDPOINT]
        database: [ADX_DATABASE]
        updateFrequency: 2m
        Retry:
          Delay: 3s
          MaxJitter: 5s
          Attempts: 5
      Chaos:
        Enabled: false
        Failure:
          PerMessage: 10 # Every 10 messages 1 wont translate
    logging:
      adx:
        enabled: true
        endpoint: [ADX_ENDPOINT]
        database: [ADX_DATABASE]
        table: [ADX_TABLE]
        mapping: json
        Retry:
          Delay: 1s
          MaxJitter: 3s
          Attempts: 3
      fluentd:
        enabled: false
        socketPath: /var/run/mdsd/default_fluent.socket
    Metrics:
      inmem:
        enabled: true
        interval: 1m
        retain: 24h
      prometheus:
        Enabled: true
        Port: 9090
        Path: /metrics
      statsd:
        Enabled: false
        Service: 1.1.1.1:80
