apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: translator
        image: [REGISTRY]/translator:v0.1.0
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
