apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: translator
        image: [REGISTRY]/streamliner:v0.1.0
        imagePullPolicy: Always
        env:
        - name: AZURE_TENANT_ID
          value: '${AZURE_TENANT_ID}'
        - name: AZURE_CLIENT_ID
          value: '${AZURE_CLIENT_ID}'
        - name: AZURE_CLIENT_SECRET
          value: '${AZURE_CLIENT_SECRET}'
        - name: AZURE_EVENTHUB_CONNECTIONSTRING
          value: '${AZURE_EVENTHUB_CONNECTIONSTRING}'
        - name: EVENT_GRID_PRIMARY_KEY
          value: '${EVENT_GRID_PRIMARY_KEY}'
        - name: EVENT_GRID_SECONDARY_KEY
          value: '${EVENT_GRID_SECONDARY_KEY}'
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
