resources:
- configmap.yaml
- deployment.yaml
secretGenerator:
- name: ha-secrets-primary-backup
  namespace: streamliner
  envs:
  - .env
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated