resources:
- configmap.yaml
- deployment.yaml
secretGenerator:
- name: github.com/Azure/streamliner/samples/ha-secrets-primary-backup
  namespace: github.com/Azure/streamliner/samples/ha
  envs:
  - .env
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated